### PR TITLE
Fix "undefined method safe_append=" on Ruby 3.0.0

### PR DESCRIPTION
**Pull request by mattbrictson**

### CODE REVIEW

**Comment by deepakmahakale** [comment]
Any updates on this one? xray-rails is breaking on ruby 3.0

**Comment by mattbrictson** [comment]
> Any updates on this one? xray-rails is breaking on ruby 3.0

I'm using this branch on a Ruby 3.0.0 project and it seems to work. I am reluctant to merge this because CI is broken so I can't be sure it works on other versions of Ruby. Unfortunately I don't have time to work on fixing CI or tending to the other backlog of issues that need to be addressed before cutting a new release.

For now you can depend on this branch directly, like this:

```ruby
gem "xray-rails", git: "https://github.com/brentd/xray-rails.git", branch: "bugs/ruby-3.0.0"
```

**Comment by deepakmahakale** [comment]
Can we please release this version?
Anything I can do to help?

**Comment by deepakmahakale** [comment]
### The fix I am using `xray-rails`

Ruby 3.0.1
Rails 6.1.4

**Gemfile**
```ruby
gem "xray-rails", git: "https://github.com/brentd/xray-rails.git", branch: "bugs/ruby-3.0.0"
```

**app/views/layouts/application.html.erb**
```erb
<%= javascript_include_tag 'xray', nonce: true if Rails.env.development? %>
<%= stylesheet_link_tag 'xray', nonce: true if Rails.env.development? %> 
```

**Comment by graaff** [comment]
The fix in this PR only works on Ruby 2.7+. If compatibility with older, unsupported, ruby versions is required then the ruby2_keywords method should be used. See https://www.ruby-lang.org/en/news/2019/12/12/separation-of-positional-and-keyword-arguments-in-ruby-3-0/

**Comment by goofansu** [comment]
Fixed my problem with this branch. I confirm it works on Ruby 3.2.2 and Rails 7.0.4.3.

**Comment by mamantoha** [comment]
Hi @brentd. Will you be merging this PR?

**Comment by brentd** [comment]
Merged. I will cut a release in the next few days. Sorry for the long hiatus!

**Comment by tyrro** [comment]
Hello @brentd, Do you have any plans or timeline for the release? Thanks!

**Comment by brentd** [comment]
@tyrro 0.3.3 has been released

**Comment by brentd** [comment]
Sorry again for the lack of activity. I am working on a rewrite of xray-rails that will remove the dependency on jquery, and other very old things like coffeescript.

**Comment by evolve2k** [comment]
This is such a useful gem especially for those new to rails. Really appreciate you putting time into upgrading the project.

**Pull request merged**
