### PR TITLE
Use module prepend if available (alias_method_chain deprecation)

### PR DESCRIPTION
**Pull request by 2called-chaos**
See #81 for discussion

### CODE REVIEW

**Comment by mattbrictson** [comment]
Thanks for the PR! Could you investigate the test failures?

**Comment by 2called-chaos** [comment]
Hmm the problem is that the test addresses :render_without_xray and I don't really know enough about rspec to fix this except removing the calls to this method. But apart from that I get the same error for current master branch, maybe a dependency change?

**Comment by mattbrictson** [comment]
The master build is currently passing. The most recent build is from yesterday: https://travis-ci.org/brentd/xray-rails/builds/203249057

Next time I have a chance I'll see if I can figure out the rspec errors on this PR.

**Comment by mattbrictson** [comment]
Thanks again @2called-chaos for your help on this and originally raising the issue. I am going to close this PR in favor of a simpler hack (see also https://github.com/bootstrap-ruby/rails-bootstrap-forms/pull/267) in PR #83.

**Pull request closed without merging**
